name: flutter_kiwi
description: A Flutter example for kiwi.
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  kiwi:
    path: ../../packages/kiwi/

dependency_overrides:
  kiwi:
    path: ../../packages/kiwi/
  kiwi_generator:
    path: ../../packages/kiwi_generator/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  kiwi_generator:
    path: ../../packages/kiwi_generator/

flutter:
  uses-material-design: true