name: dart_kiwi
description: A sample command-line application as an example for kiwi.
version: 1.0.0+2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  kiwi:
    path: ../../packages/kiwi/

dependency_overrides:
  kiwi:
    path: ../../packages/kiwi/
  kiwi_generator:
    path: ../../packages/kiwi_generator/
  
dev_dependencies:
  test: ^1.26.3
  build_runner: ^2.10.4
  kiwi_generator:
    path: ../../packages/kiwi_generator/