name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.2.1
homepage: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
repository: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
issue_tracker: https://github.com/gbtb16/kiwi/issues

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  analyzer: ^8.2.0
  build: ^3.0.0
  build_config: ^1.1.1
  built_collection: ^5.1.1
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  kiwi: ^5.0.1
  path: ^1.9.1
  source_gen: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.15
  build_test: ^3.3.1
  package_config: ^2.1.0
  test: ^1.26.3

topics:
  - kiwi
  - automatic-generator
  - dependency-injector
