name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.2.1
homepage: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
repository: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
issue_tracker: https://github.com/gbtb16/kiwi/issues

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  analyzer: ">=5.13.0 <6.5.0"
  build: 2.4.1
  build_config: ^1.1.1
  built_collection: ^5.1.1
  code_builder: ^4.11.0
  dart_style: ^2.3.6
  kiwi: ^5.0.1
  path: ^1.9.1
  source_gen: ">=1.5.0 <2.0.0"

dev_dependencies:
  build_runner: ^2.4.13
  build_test: ^2.2.2
  test: ^1.26.3

dependency_overrides:
  build: 2.4.1
  build_resolvers: 2.4.1

topics:
  - kiwi
  - automatic-generator
  - dependency-injector
