name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.3.0
homepage: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
repository: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
issue_tracker: https://github.com/gbtb16/kiwi/issues

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  analyzer: ^8.2.0
  build: ^4.0.3
  build_config: ^1.2.0
  built_collection: ^5.1.1
  code_builder: ^4.11.1
  dart_style: ^3.0.0
  kiwi:
    path: ../kiwi
  path: ^1.9.1
  source_gen: ^4.1.1

dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  test: ^1.26.3

topics:
  - kiwi
  - automatic-generator
  - dependency-injector